// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package sumermcu_gpio_reg_pkg;

    localparam SUMERMCU_GPIO_REG_DATA_WIDTH = 32;
    localparam SUMERMCU_GPIO_REG_MIN_ADDR_WIDTH = 3;
    localparam SUMERMCU_GPIO_REG_SIZE = 'h8;

    

    typedef struct {
        logic [15:0] next;
    } sumermcu_gpio_reg__IDR__STATE__in_t;

    typedef struct {
        sumermcu_gpio_reg__IDR__STATE__in_t STATE;
    } sumermcu_gpio_reg__IDR__in_t;

    typedef struct {
        sumermcu_gpio_reg__IDR__in_t IDR;
    } sumermcu_gpio_reg__in_t;

    typedef struct {
        logic [15:0] value;
    } sumermcu_gpio_reg__IDR__STATE__out_t;

    typedef struct {
        sumermcu_gpio_reg__IDR__STATE__out_t STATE;
    } sumermcu_gpio_reg__IDR__out_t;

    typedef struct {
        logic [15:0] value;
    } sumermcu_gpio_reg__ODR__STATE__out_t;

    typedef struct {
        sumermcu_gpio_reg__ODR__STATE__out_t STATE;
    } sumermcu_gpio_reg__ODR__out_t;

    typedef struct {
        sumermcu_gpio_reg__IDR__out_t IDR;
        sumermcu_gpio_reg__ODR__out_t ODR;
    } sumermcu_gpio_reg__out_t;
endpackage
